version: '3.8'

services:
  backend:
    build: ./Back
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./Back:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./Back/.env
    environment:
      - DB_HOST=db
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: NutriTrain
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: